export const data = [
  {
    nomor: 1,
    namaUsaha: "Among Coffee",
    pemilik: "Among tani",
    dusun: "Reco",
    produk: "Kopi Arabika",
    kegiatanUsaha: "Usaha minuman",
  },
  {
    nomor: 2,
    namaUsaha: "Tembakau Among Tani",
    pemilik: "Among tani",
    dusun: "Reco",
    produk: "Tembakau",
    kegiatanUsaha: "Usaha pertanian",
  },
  {
    nomor: 3,
    namaUsaha: "Laras Boga",
    pemilik: "Suwanti",
    dusun: "Anggrunggondok",
    produk: "Kue kering",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 4,
    namaUsaha: "Jual kijing dan pawon",
    pemilik: "Bambang",
    dusun: "Banyuurip",
    produk: "Batu nisan dan pawon",
    kegiatanUsaha: "Usaha kerajinan",
  },
  {
    nomor: 5,
    namaUsaha: "Kletuk Combro",
    pemilik: "Barno",
    dusun: "Anggrunggondok",
    produk: "Kletuk combro",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 6,
    namaUsaha: "Carica Sumbing Segar",
    pemilik: "Chafid",
    dusun: "Reco",
    produk: "Manisan carica",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 7,
    namaUsaha: "Rio Coffee",
    pemilik: "Untung",
    dusun: "Reco",
    produk: "Kopi Arabika",
    kegiatanUsaha: "Usaha minuman",
  },
  {
    nomor: 8,
    namaUsaha: "Bakso Ikatan Cinta",
    pemilik: "Nirwati",
    dusun: "Anggrunggondok",
    produk: "Bakso",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 9,
    namaUsaha: "Kinant Project",
    pemilik: "Verry",
    dusun: "Anggrunggondok",
    produk: "Parcel dan packaging",
    kegiatanUsaha: "Usaha kerajinan",
  },
  {
    nomor: 10,
    namaUsaha: "Bisatani",
    pemilik: "Zaki",
    dusun: "Reco",
    produk: "Pupuk dan penyubur tanaman",
    kegiatanUsaha: "Usaha pertanian",
  },
  {
    nomor: 11,
    namaUsaha: "Rumah Kopi Anggrung",
    pemilik: "Yudi",
    dusun: "Anggrunggondok",
    produk: "Kopi Arabika",
    kegiatanUsaha: "Usaha minuman",
  },
  {
    nomor: 12,
    namaUsaha: "Ebenhaezer farm",
    pemilik: "Sigit",
    dusun: "Reco",
    produk: "Ayam pedaging pejantan",
    kegiatanUsaha: "Usaha peternakan",
  },
  {
    nomor: 13,
    namaUsaha: "Sukirno Tas",
    pemilik: "Sukirno",
    dusun: "Reco",
    produk: "Tas",
    kegiatanUsaha: "Usaha kerajinan",
  },
  {
    nomor: 14,
    namaUsaha: "Mesin Rajang Tri",
    pemilik: "Tri",
    dusun: "Anggrunggondok",
    produk: "Mesin rajang tembakau",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 15,
    namaUsaha: "Dadi Panuntun",
    pemilik: "Dadi Panuntun",
    dusun: "Anggrunggondok",
    produk: "Mesin rajang tembakau",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 16,
    namaUsaha: "Alfa Hidayatul",
    pemilik: "Alfa Hidayatul",
    dusun: "Anggrunggondok",
    produk: "Mesin rajang tembakau",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 17,
    namaUsaha: "Azis Tralis",
    pemilik: "Pardi",
    dusun: "Anggrunggondok",
    produk: "Tralis",
    kegiatanUsaha: "Usaha furnitur",
  },
  {
    nomor: 18,
    namaUsaha: "Mesin Rajang Mahrodi",
    pemilik: "Mahrodi",
    dusun: "Anggrunggondok",
    produk: "Mesin rajang",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 19,
    namaUsaha: "Mesin Rajang Ipnu",
    pemilik: "Ipnu",
    dusun: "Anggrunggondok",
    produk: "Mesin rajang",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 20,
    namaUsaha: "Kurnia Jaya",
    pemilik: "Oscar Suhatman",
    dusun: "Reco",
    produk: "Mesin rajang",
    kegiatanUsaha: "Usaha peralatan",
  },
  {
    nomor: 21,
    namaUsaha: "Furnitur Parjio",
    pemilik: "Parjio",
    dusun: "Anggrunggondok",
    produk: "Furnitur",
    kegiatanUsaha: "Usaha furnitur",
  },
  {
    nomor: 22,
    namaUsaha: "Warung Nadila",
    pemilik: "Nadila",
    dusun: "Anggrunggondok",
    produk: "Bakso dan makanan ringan",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 23,
    namaUsaha: "Strawberry Garden",
    pemilik: "Panjang",
    dusun: "Yososari",
    produk: "Strawberry",
    kegiatanUsaha: "Usaha pertanian",
  },
  {
    nomor: 24,
    namaUsaha: "Warung Bu Wanti depan SD",
    pemilik: "Wanti",
    dusun: "Anggrungondok",
    produk: "Warung",
    kegiatanUsaha: "Usaha perdagangan",
  },
  {
    nomor: 25,
    namaUsaha: "Warung Bu Supami depan SD",
    pemilik: "Supami",
    dusun: "Anggrunggondok",
    produk: "Warung",
    kegiatanUsaha: "Usaha perdagangan",
  },
  {
    nomor: 26,
    namaUsaha: "Toko Bu Sartiyah",
    pemilik: "Suyatmo",
    dusun: "Anggrunggondok",
    produk: "Gorengan dan makanan ringan",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 27,
    namaUsaha: "Toko Iska",
    pemilik: "Purwanti",
    dusun: "Anggrunggondok",
    produk: "Toko kelontong",
    kegiatanUsaha: "Usaha perdagangan",
  },
  {
    nomor: 28,
    namaUsaha: "Bakso Lesehan",
    pemilik: "Muharno",
    dusun: "Anggrunggondok",
    produk: "Bakso dan gorengan",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 29,
    namaUsaha: "Giono Konveksi",
    pemilik: "Giono",
    dusun: "Reco",
    produk: "Kostum tari",
    kegiatanUsaha: "Konveksi",
  },
  {
    nomor: 30,
    namaUsaha: "Bengkel Suranto",
    pemilik: "Suranto",
    dusun: "Reco",
    produk: "Bengkel motor",
    kegiatanUsaha: "Usaha jasa",
  },
  {
    nomor: 31,
    namaUsaha: "Ayam Pedaging Dahyono",
    pemilik: "Dahyono",
    dusun: "Reco",
    produk: "Ayam pedaging",
    kegiatanUsaha: "Usaha peternakan",
  },
  {
    nomor: 32,
    namaUsaha: "Gino Kusen",
    pemilik: "Gino",
    dusun: "Reco",
    produk: "Kusen",
    kegiatanUsaha: "Usaha furnitur",
  },
  {
    nomor: 33,
    namaUsaha: "Jo Coffee",
    pemilik: "Harjo",
    dusun: "Reco",
    produk: "Kopi",
    kegiatanUsaha: "Usaha minuman",
  },
  {
    nomor: 34,
    namaUsaha: "Mak Nur",
    pemilik: "Harjo",
    dusun: "Reco",
    produk: "Berbahan gorengan",
    kegiatanUsaha: "Usaha makanan",
  },
  {
    nomor: 35,
    namaUsaha: "Tralis",
    pemilik: "-",
    dusun: "Reco",
    produk: "Tralis",
    kegiatanUsaha: "Usaha furnitur",
  },
  {
    nomor: 36,
    namaUsaha: "Co Cell",
    pemilik: "-",
    dusun: "Anggrunggondok",
    produk: "Pulsa dan agen pembayaran",
    kegiatanUsaha: "Usaha Jasa",
  },
];
